import logging
import hashlib
import json
import time
import re
import requests
from hiveai.config import HIVE_API_NODES, HIVE_REFINED_TAG
from hiveai.models import GoldenBook, utcnow

logger = logging.getLogger(__name__)

MAX_POST_SIZE = 60000


def generate_permlink(title):
    permlink = title.lower().strip()
    permlink = re.sub(r'[^a-z0-9\s-]', '', permlink)
    permlink = re.sub(r'\s+', '-', permlink)
    permlink = permlink[:200]
    timestamp = str(int(time.time()))
    return f"hiveai-{permlink}-{timestamp}"


def generate_tags(topic, content_hash):
    tags = [HIVE_REFINED_TAG]

    hash_prefix = f"knowledgehash{content_hash[0].lower()}"
    tags.append(hash_prefix)

    topic_words = topic.lower().split()
    for word in topic_words[:2]:
        clean = re.sub(r'[^a-z0-9]', '', word)
        if clean and len(clean) >= 3 and clean not in tags:
            tags.append(clean)

    while len(tags) < 5:
        tags.append("hiveai")
        break

    return tags[:5]


def split_content(content, max_size=MAX_POST_SIZE):
    if len(content.encode('utf-8')) <= max_size:
        return [content]

    parts = []
    paragraphs = content.split('\n\n')
    current_part = ""

    for para in paragraphs:
        test = current_part + "\n\n" + para if current_part else para
        if len(test.encode('utf-8')) > max_size - 500:
            if current_part:
                parts.append(current_part)
            current_part = para
        else:
            current_part = test

    if current_part:
        parts.append(current_part)

    return parts


def format_post_body(book):
    body = book.content

    body += "\n\n---\n"
    body += f"\n**Content Hash (SHA-256):** `{book.content_hash}`\n"
    body += f"\n**Sources:** {book.source_count} web sources consulted\n"
    body += f"\n**Knowledge Triples:** {book.triple_count} facts extracted\n"
    body += f"\n*Generated by HiveAI Knowledge Refinery*\n"

    return body


def publish_to_hive(book, author, db):
    if not isinstance(book, GoldenBook):
        raise ValueError("Invalid book object")

    permlink = generate_permlink(book.title)
    tags = generate_tags(book.title, book.content_hash)

    post_body = format_post_body(book)
    parts = split_content(post_body)

    json_metadata = json.dumps({
        "app": "hiveai-refinery/1.0",
        "format": "markdown",
        "tags": tags,
        "content_hash": book.content_hash,
        "source_count": book.source_count,
        "triple_count": book.triple_count,
        "word_count": book.word_count,
        "source_urls": book.source_urls[:20],
        "type": "golden_book",
    })

    operations = []
    if len(parts) == 1:
        operations.append([
            "comment",
            {
                "parent_author": "",
                "parent_permlink": tags[0],
                "author": author,
                "permlink": permlink,
                "title": book.title,
                "body": parts[0],
                "json_metadata": json_metadata,
            }
        ])
    else:
        for i, part in enumerate(parts):
            if i == 0:
                operations.append([
                    "comment",
                    {
                        "parent_author": "",
                        "parent_permlink": tags[0],
                        "author": author,
                        "permlink": permlink,
                        "title": book.title,
                        "body": f"*Part 1 of {len(parts)}*\n\n---\n\n{part}",
                        "json_metadata": json_metadata,
                    }
                ])
            else:
                part_permlink = f"{permlink}-part-{i + 1}"
                operations.append([
                    "comment",
                    {
                        "parent_author": author,
                        "parent_permlink": permlink,
                        "author": author,
                        "permlink": part_permlink,
                        "title": "",
                        "body": f"*Part {i + 1} of {len(parts)}*\n\n---\n\n{part}",
                        "json_metadata": json_metadata,
                    }
                ])

    beneficiaries_op = [
        "comment_options",
        {
            "author": author,
            "permlink": permlink,
            "max_accepted_payout": "0.000 SBD",
            "percent_hbd": 10000,
            "allow_votes": True,
            "allow_curation_rewards": True,
            "extensions": [[0, {"beneficiaries": [{"account": "null", "weight": 10000}]}]],
        }
    ]
    operations.append(beneficiaries_op)

    book.status = "pending_signature"
    book.hive_permlink = permlink
    book.hive_author = author
    db.commit()

    logger.info(f"Prepared {len(operations)} operations for publishing '{book.title}' by @{author}")

    return {
        "status": "ready_to_sign",
        "permlink": permlink,
        "author": author,
        "tags": tags,
        "operations": operations,
        "parts": len(parts),
        "message": "Operations prepared. Use Hive Keychain or HAS to sign and broadcast.",
    }
