"""
hiveai/lora/exporter.py

Export training pairs from SQLite to training-ready formats for LoRA fine-tuning.

Two export formats:
  1. Alpaca JSONL:  {"instruction": "...", "input": "", "output": "..."}
  2. Rich JSONL:    Full metadata for analysis and curriculum learning

Two data sources:
  1. training_pairs table — pairs generated by distiller or brain_mine.py
  2. golden_books — existing books converted to (instruction, response) pairs

Usage:
  from hiveai.lora.exporter import export_training_pairs
  count = export_training_pairs(db, "loras/training_data/coding_v1.jsonl")
"""
import json
import logging
import os
import re
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

from hiveai.lora.distiller import _is_hive_content
from hiveai.config import LORA_EXPORT_QUALITY
MIN_QUALITY = LORA_EXPORT_QUALITY

# ---------------------------------------------------------------------------
# Difficulty classification — keywords that indicate complexity level
# ---------------------------------------------------------------------------
BEGINNER_SIGNALS = [
    "what is", "explain", "introduction", "basic", "beginner", "simple",
    "getting started", "how to", "tutorial", "fundamentals",
]
EXPERT_SIGNALS = [
    "production", "optimize", "under the hood", "internals", "cpython",
    "at scale", "concurrent", "distributed", "architecture", "benchmark",
    "memory management", "garbage collection", "metaclass", "descriptor",
    "under load", "fault tolerance", "system design",
]

# ---------------------------------------------------------------------------
# Diverse question patterns for section header conversion
# ---------------------------------------------------------------------------
QUESTION_PATTERNS = [
    "Explain {header} in the context of {topic}. Include practical code examples.",
    "What are the key concepts and best practices for {header} when working with {topic}?",
    "How does {header} work in {topic}? Show implementation details with code.",
    "Describe {header} as it relates to {topic}. What are common pitfalls?",
    "What should a developer know about {header} in {topic}? Provide examples.",
]


def _classify_difficulty(instruction: str, response: str) -> str:
    """
    Classify training pair difficulty: beginner, intermediate, or expert.
    Based on instruction complexity, response depth, and vocabulary.
    """
    text = (instruction + " " + response).lower()

    expert_hits = sum(1 for s in EXPERT_SIGNALS if s in text)
    beginner_hits = sum(1 for s in BEGINNER_SIGNALS if s in text)

    # Response complexity signals
    word_count = len(response.split())
    code_blocks = len(re.findall(r"```", response)) // 2

    if expert_hits >= 3 or (word_count >= 1000 and code_blocks >= 4):
        return "expert"
    elif beginner_hits >= 2 and expert_hits == 0 and word_count < 600:
        return "beginner"
    else:
        return "intermediate"


def _is_hive_pair(pair: dict) -> bool:
    """Check if a training pair is Hive-domain content.
    Uses source tag (fast path) or content detection (fallback for legacy pairs).
    """
    # Fast path: pairs from Hive-specific generation
    source = pair.get("source", "")
    if source == "human_teaching_hive":
        return True

    # Fast path: topic matches known Hive terms
    topic = (pair.get("topic", "") or "").lower()
    if any(term in topic for term in ("hive", "beem", "dhive", "dpos", "hbd", "haf")):
        return True

    # Slow path: content-based detection for legacy pairs
    text = pair.get("instruction", "") + " " + pair.get("response", "")
    is_hive, _ = _is_hive_content(text, topic)
    return is_hive


def export_training_pairs(db, output_path: str, min_quality: float = MIN_QUALITY,
                          format: str = "alpaca") -> int:
    """
    Export all eligible training pairs to a JSONL file.

    Args:
        db: SQLAlchemy session
        output_path: Where to write the JSONL file
        min_quality: Minimum quality threshold
        format: "alpaca" (standard) or "rich" (with metadata)

    Returns count of exported pairs.
    """
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)

    pairs = []

    # Source 1: existing training_pairs table
    pairs.extend(_load_training_pairs(db, min_quality))

    # Source 2: derive from golden_books
    pairs.extend(_derive_from_books(db, min_quality))

    if not pairs:
        logger.warning("No eligible training pairs found to export")
        return 0

    # Deduplicate by instruction text (exact match) before writing
    seen_instructions = set()
    unique_pairs = []
    for pair in pairs:
        key = pair["instruction"].strip().lower()[:200]
        if key not in seen_instructions:
            seen_instructions.add(key)
            unique_pairs.append(pair)

    # Domain weighting: Hive pairs appear 2x for stronger domain learning.
    # Appended AFTER dedup so copies aren't filtered out.
    # Use shallow copies (not references) to avoid shared-state bugs.
    import random
    hive_pairs = [p for p in unique_pairs if _is_hive_pair(p)]
    unique_pairs.extend([dict(p) for p in hive_pairs])
    logger.info(f"Domain weighting: {len(hive_pairs)} Hive pairs oversampled (2x)")

    # Sort by difficulty for curriculum learning (beginner → expert).
    # Random tiebreaker within each band spreads oversampled duplicates apart,
    # preventing gradient instability from seeing the same pair twice in a row.
    difficulty_order = {"beginner": 0, "intermediate": 1, "expert": 2}
    unique_pairs.sort(key=lambda p: (
        difficulty_order.get(p.get("difficulty", "intermediate"), 1),
        random.random(),
    ))

    with open(output_path, "w", encoding="utf-8") as f:
        for pair in unique_pairs:
            if format == "rich":
                record = _to_rich_format(pair)
            else:
                record = _to_alpaca_format(pair)
            f.write(json.dumps(record, ensure_ascii=False) + "\n")

    logger.info(f"Exported {len(unique_pairs)} training pairs to {output_path} (format={format})")

    # Log difficulty + domain distribution
    diff_counts = {}
    for p in unique_pairs:
        d = p.get("difficulty", "unknown")
        diff_counts[d] = diff_counts.get(d, 0) + 1
    hive_count = sum(1 for p in unique_pairs if _is_hive_pair(p))
    logger.info(f"Difficulty distribution: {diff_counts}")
    logger.info(f"Domain distribution: {hive_count} Hive (incl. oversampled), {len(unique_pairs) - hive_count} general")

    return len(unique_pairs)


def _to_alpaca_format(pair: dict) -> dict:
    """Standard Alpaca format with context in the input field."""
    input_context = ""
    # Use input field for context when available (e.g., topic hints)
    if pair.get("topic"):
        input_context = f"Topic: {pair['topic']}"

    return {
        "instruction": pair["instruction"],
        "input": input_context,
        "output": pair["response"],
    }


def _to_rich_format(pair: dict) -> dict:
    """Rich format with full metadata for analysis and curriculum learning."""
    return {
        "instruction": pair["instruction"],
        "input": f"Topic: {pair.get('topic', '')}" if pair.get("topic") else "",
        "output": pair["response"],
        "metadata": {
            "source": pair.get("source", "unknown"),
            "topic": pair.get("topic", ""),
            "quality": pair.get("quality", 0.0),
            "difficulty": pair.get("difficulty", "intermediate"),
            "domain": "hive" if _is_hive_pair(pair) else "general",
            "word_count": len(pair["response"].split()),
            "code_blocks": len(re.findall(r"```", pair["response"])) // 2,
            "template": pair.get("template", ""),
            "created_at": pair.get("created_at", datetime.now(timezone.utc).isoformat()),
        },
    }


def _load_training_pairs(db, min_quality: float) -> list:
    """Load eligible pairs from the training_pairs table with metadata."""
    from hiveai.models import TrainingPair

    rows = db.query(TrainingPair).filter(
        TrainingPair.is_eligible == True,
        TrainingPair.quality >= min_quality,
    ).all()

    pairs = []
    for row in rows:
        if row.instruction and row.response:
            difficulty = _classify_difficulty(row.instruction, row.response)
            pairs.append({
                "instruction": row.instruction,
                "response": row.response,
                "source": row.source or "self_distill",
                "topic": row.topic or "",
                "quality": row.quality or 0.0,
                "difficulty": difficulty,
                "created_at": row.created_at.isoformat() if row.created_at else "",
            })

    logger.info(f"Loaded {len(pairs)} pairs from training_pairs table")
    return pairs


def _derive_from_books(db, min_quality: float) -> list:
    """
    Convert golden_books content into training pairs.

    For each high-quality book:
      - Whole-book pair (if 200-2000 words): "Write a guide" → full content
      - Section pairs (if section ≥80 words): diverse question → section content
      - Extraction pairs: raw text → extracted triples (teaches extraction skill)
    """
    from hiveai.models import GoldenBook, BookSection

    books = db.query(GoldenBook).filter(
        GoldenBook.quality_score >= min_quality,
        GoldenBook.status.in_(["published", "ready", "draft"]),
    ).all()

    pairs = []
    pattern_idx = 0  # rotate through question patterns for diversity

    for book in books:
        if not book.content:
            continue

        word_count = len(book.content.split())

        # Whole-book skill pair — only if manageable length (200-2000 words)
        if 200 <= word_count <= 2000:
            whole_instruction = f"Write a comprehensive technical guide about: {book.title}"
            pairs.append({
                "instruction": whole_instruction,
                "response": book.content,
                "source": "golden_book",
                "topic": book.title,
                "quality": book.quality_score or 0.7,
                "difficulty": _classify_difficulty(whole_instruction, book.content),
            })

        # Section-level pairs with diverse question patterns
        sections = db.query(BookSection).filter(BookSection.book_id == book.id).all()
        for section in sections:
            if not section.header or not section.content:
                continue
            section_words = len(section.content.split())
            if section_words < 80:
                continue  # Too short for meaningful training
            # Skip sections that are just lists of links or references
            if section.content.count("http") > 5 and section_words < 150:
                continue

            instruction = _header_to_question(section.header, book.title, pattern_idx)
            pattern_idx = (pattern_idx + 1) % len(QUESTION_PATTERNS)

            # Section quality heuristic (better than just word count)
            section_quality = _estimate_section_quality(section.content, section_words)

            if section_quality >= min_quality:
                pairs.append({
                    "instruction": instruction,
                    "response": section.content,
                    "source": "golden_book",
                    "topic": book.title,
                    "quality": section_quality,
                    "difficulty": _classify_difficulty(instruction, section.content),
                })

        # NOTE: Extraction pairs (knowledge graph triple extraction) removed.
        # They contain no code blocks and would score ≤0.49 under the coding-focused
        # scorer (MIN_CODE_BLOCKS=1 hard gate). Previously hardcoded to quality=0.75
        # which bypassed the scorer — that masked the mismatch.

    logger.info(f"Derived {len(pairs)} pairs from {len(books)} golden books")
    return pairs


def _estimate_section_quality(content: str, word_count: int) -> float:
    """
    Estimate quality of a book section for training purposes.
    More nuanced than just word count — checks for substance.
    """
    quality = 0.0

    # Word count component (diminishing returns)
    if word_count >= 500:
        quality += 0.35
    elif word_count >= 300:
        quality += 0.28
    elif word_count >= 150:
        quality += 0.20
    elif word_count >= 80:
        quality += 0.10

    # Has code examples
    code_blocks = len(re.findall(r"```", content)) // 2
    if code_blocks >= 2:
        quality += 0.25
    elif code_blocks >= 1:
        quality += 0.15

    # Has specific facts (numbers, technical terms)
    sentences = [s.strip() for s in re.split(r'[.!?]+', content) if len(s.strip()) > 10]
    if sentences:
        fact_sentences = sum(1 for s in sentences if re.search(r'\d+|`\w+`|[A-Z][a-z]+[A-Z]', s))
        fact_ratio = fact_sentences / len(sentences)
        quality += min(fact_ratio * 0.25, 0.20)

    # Has structured content (lists, headers)
    if re.search(r"^[\s]*[-*]\s+", content, re.MULTILINE):
        quality += 0.10

    # Sentence count (at least 3 for coherent content)
    if len(sentences) >= 5:
        quality += 0.10
    elif len(sentences) >= 3:
        quality += 0.05

    return round(min(quality, 1.0), 2)


def _header_to_question(header: str, book_title: str, pattern_idx: int = 0) -> str:
    """
    Convert a section header into a diverse natural question instruction.
    Rotates through patterns to avoid repetitive "Explain X in context of Y" monotony.
    """
    # Strip markdown heading markers
    clean = re.sub(r"^#+\s*", "", header).strip()

    # If it already looks like a question, use it directly
    if clean.endswith("?"):
        return clean

    # Rotate through diverse question patterns
    pattern = QUESTION_PATTERNS[pattern_idx % len(QUESTION_PATTERNS)]
    return pattern.format(header=clean, topic=book_title)


def export_with_sampling(db, output_path: str, target_count: int = 500,
                         min_quality: float = MIN_QUALITY, format: str = "alpaca") -> int:
    """
    Quality-aware stratified export — creates a balanced training set.

    Instead of exporting ALL pairs, selects a target number with:
      - Difficulty balance: ~20% beginner, ~60% intermediate, ~20% expert
      - Quality priority: highest quality pairs selected first within each stratum
      - Topic diversity: no more than 10 pairs from any single topic

    This produces a smaller but more effective training set for LoRA.
    """
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)

    # Gather all candidates
    all_pairs = []
    all_pairs.extend(_load_training_pairs(db, min_quality))
    all_pairs.extend(_derive_from_books(db, min_quality))

    if not all_pairs:
        logger.warning("No eligible training pairs found")
        return 0

    # Deduplicate
    seen = set()
    unique = []
    for p in all_pairs:
        key = p["instruction"].strip().lower()[:200]
        if key not in seen:
            seen.add(key)
            unique.append(p)

    # Stratify by difficulty
    strata = {"beginner": [], "intermediate": [], "expert": []}
    for p in unique:
        d = p.get("difficulty", "intermediate")
        strata.get(d, strata["intermediate"]).append(p)

    # Sort each stratum by quality (highest first)
    for d in strata:
        strata[d].sort(key=lambda p: p.get("quality", 0), reverse=True)

    # Target distribution
    targets = {
        "beginner": int(target_count * 0.20),
        "intermediate": int(target_count * 0.60),
        "expert": int(target_count * 0.20),
    }

    # Sample with topic diversity cap
    selected = []
    for difficulty, target in targets.items():
        pool = strata[difficulty]
        topic_counts = {}
        for p in pool:
            topic = p.get("topic", "unknown")
            if topic_counts.get(topic, 0) >= 10:
                continue  # Topic cap
            topic_counts[topic] = topic_counts.get(topic, 0) + 1
            selected.append(p)
            if len([s for s in selected if s.get("difficulty") == difficulty]) >= target:
                break

    # If we didn't fill quotas, redistribute from other strata
    if len(selected) < target_count:
        remaining_pool = [p for p in unique if p not in selected]
        remaining_pool.sort(key=lambda p: p.get("quality", 0), reverse=True)
        for p in remaining_pool:
            if len(selected) >= target_count:
                break
            selected.append(p)

    # Domain weighting: ensure Hive pairs are well-represented (2x)
    import random
    hive_selected = [p for p in selected if _is_hive_pair(p)]
    if hive_selected:
        selected.extend([dict(p) for p in hive_selected])
        logger.info(f"Domain weighting: {len(hive_selected)} Hive pairs oversampled in sampled export")

    # Curriculum sort: beginner → intermediate → expert
    # Random tiebreaker spreads oversampled duplicates within each band
    difficulty_order = {"beginner": 0, "intermediate": 1, "expert": 2}
    selected.sort(key=lambda p: (
        difficulty_order.get(p.get("difficulty", "intermediate"), 1),
        random.random(),
    ))

    with open(output_path, "w", encoding="utf-8") as f:
        for pair in selected:
            record = _to_rich_format(pair) if format == "rich" else _to_alpaca_format(pair)
            f.write(json.dumps(record, ensure_ascii=False) + "\n")

    # Log stats
    final_dist = {}
    for p in selected:
        d = p.get("difficulty", "unknown")
        final_dist[d] = final_dist.get(d, 0) + 1
    avg_quality = sum(p.get("quality", 0) for p in selected) / len(selected) if selected else 0

    logger.info(
        f"Sampled {len(selected)}/{len(unique)} pairs to {output_path} (target={target_count}) | "
        f"Distribution: {final_dist} | Avg quality: {avg_quality:.2f}"
    )
    return len(selected)


def validate_export(jsonl_path: str) -> dict:
    """
    Validate an exported JSONL file for training readiness.

    Checks:
      - All records have required fields (instruction, output)
      - No empty/very short responses
      - No truncated code blocks
      - No duplicate instructions
      - Word count distribution stats
    """
    issues = []
    stats = {"total": 0, "valid": 0, "duplicates": 0, "empty_responses": 0,
             "truncated_code": 0, "word_counts": []}
    seen_instructions = set()

    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue

            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                issues.append(f"Line {line_num}: invalid JSON")
                continue

            stats["total"] += 1

            # Required fields
            instruction = record.get("instruction", "")
            output = record.get("output", "")

            if not instruction:
                issues.append(f"Line {line_num}: missing instruction")
                continue
            if not output:
                stats["empty_responses"] += 1
                issues.append(f"Line {line_num}: empty output")
                continue

            # Duplicate check
            key = instruction.strip().lower()[:200]
            if key in seen_instructions:
                stats["duplicates"] += 1
            else:
                seen_instructions.add(key)

            # Truncated code blocks
            backtick_count = output.count("```")
            if backtick_count % 2 != 0:
                stats["truncated_code"] += 1

            # Word count
            wc = len(output.split())
            stats["word_counts"].append(wc)

            if wc >= 50:
                stats["valid"] += 1

    # Summarize word counts
    if stats["word_counts"]:
        wcs = stats["word_counts"]
        stats["avg_word_count"] = round(sum(wcs) / len(wcs))
        stats["min_word_count"] = min(wcs)
        stats["max_word_count"] = max(wcs)
    del stats["word_counts"]

    stats["issues"] = issues[:20]  # Cap reported issues
    return stats


def derive_and_stage_from_books(db, min_quality: float = MIN_QUALITY) -> int:
    """
    Derive pairs from golden_books and stage them into the training_pairs table
    (with dedup gate). Returns count of newly staged pairs.
    """
    from hiveai.lora.dedup import is_duplicate, passes_quality_gate
    from hiveai.models import TrainingPair
    from hiveai.llm.client import embed_text

    candidates = _derive_from_books(db, min_quality)
    staged = 0

    for pair in candidates:
        quality = pair.get("quality", 0.0)
        if not passes_quality_gate(quality):
            continue
        if is_duplicate(pair["instruction"], db, quality=quality):
            continue

        try:
            embedding = embed_text(pair["instruction"])
        except Exception as e:
            logger.warning(f"Embedding failed for derived pair: {e}")
            embedding = None

        tp = TrainingPair(
            source=pair["source"],
            topic=pair["topic"],
            instruction=pair["instruction"],
            response=pair["response"],
            quality=quality,
            is_eligible=True,
            created_at=datetime.now(timezone.utc),
        )
        if embedding:
            tp.embedding = embedding

        db.add(tp)
        staged += 1

    if staged:
        db.commit()

    logger.info(f"Staged {staged} new pairs from golden books")
    return staged
