#!/usr/bin/env python3
"""Send synthetic queries through the HiveAI chat endpoint to populate telemetry.

Reads queries from data/synthetic_queries.jsonl (generated by bootstrap_datasets.py),
sends each through POST /api/chat, and logs response traces. All traffic is tagged
is_internal=true so it's separable from organic usage.

Usage:
    python scripts/synthetic_traffic.py [--input data/synthetic_queries.jsonl]
                                        [--url http://localhost:5001]
                                        [--rate 2.0]
                                        [--max-queries 200]
                                        [--phase smoke|calibration|full]

Phases:
    smoke       — 20 queries, verify pipeline works
    calibration — 200 queries, populate reranker score distributions
    full        — all queries, maximum statistical power
"""

import argparse
import json
import os
import sys
import time
import urllib.request
import urllib.error

PHASE_LIMITS = {
    "smoke": 20,
    "calibration": 200,
    "full": 99999,
}


def send_query(url: str, query: str, timeout: int = 120) -> dict:
    """Send a single query to /api/chat and return the response dict."""
    body = json.dumps({
        "message": query,
        "history": [],
    }).encode("utf-8")

    req = urllib.request.Request(
        f"{url}/api/chat",
        data=body,
        headers={
            "Content-Type": "application/json",
            "X-Internal": "true",
            "X-Frontend-Build": "synthetic-v1",
        },
    )

    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read())


def check_server(url: str) -> bool:
    """Check if the Flask server is running."""
    try:
        req = urllib.request.Request(f"{url}/health")
        with urllib.request.urlopen(req, timeout=5) as resp:
            data = json.loads(resp.read())
            return data.get("status") in ("ok", "degraded")
    except Exception:
        return False


def extract_trace_summary(response: dict) -> dict:
    """Extract key fields from response for logging."""
    trace = response.get("trace", {})
    rt = trace.get("retrieval_trace", {})
    return {
        "request_id": trace.get("request_id"),
        "answer_id": trace.get("answer_id"),
        "experiment_group": trace.get("experiment_group"),
        "response_contract": trace.get("response_contract"),
        "verified": trace.get("verified"),
        "verification_passed": trace.get("verification_passed"),
        # Retrieval trace fields
        "trace_schema_version": rt.get("trace_schema_version"),
        "cache_hit": rt.get("cache_hit"),
        "confidence_gate_evaluated": rt.get("confidence_gate_evaluated"),
        "initial_best_score": rt.get("initial_best_score"),
        "rewrite_gate_entered": rt.get("rewrite_gate_entered"),
        "rewrite_applied": rt.get("rewrite_applied"),
        "retrieval_suppressed": rt.get("retrieval_suppressed"),
        "hard_section_count": rt.get("hard_section_count"),
        # Shadow reranker fields
        "reranker_shadow_applied": rt.get("reranker_shadow_applied"),
        "reranker_best_score": rt.get("reranker_best_score"),
        "reranker_shadow_latency_ms": rt.get("reranker_shadow_latency_ms"),
        "would_suppress_reranker": rt.get("would_suppress_reranker"),
        # Entity lane
        "entities_retrieved": rt.get("entities_retrieved"),
        "soft_entity_lane_used": rt.get("soft_entity_lane_used"),
    }


def main():
    parser = argparse.ArgumentParser(description="Send synthetic traffic through HiveAI chat")
    parser.add_argument("--input", default="data/synthetic_queries.jsonl",
                        help="Input JSONL from bootstrap_datasets.py")
    parser.add_argument("--output", default="data/synthetic_results.jsonl",
                        help="Output JSONL with response traces")
    parser.add_argument("--url", default="http://localhost:5001",
                        help="Flask server URL (default: localhost:5001)")
    parser.add_argument("--rate", type=float, default=2.0,
                        help="Max requests per second (default: 2.0)")
    parser.add_argument("--max-queries", type=int, default=None,
                        help="Override max queries (overrides --phase)")
    parser.add_argument("--phase", choices=["smoke", "calibration", "full"],
                        default="calibration",
                        help="Traffic volume phase (default: calibration)")
    parser.add_argument("--timeout", type=int, default=120,
                        help="Per-request timeout in seconds (default: 120)")
    parser.add_argument("--resume", action="store_true",
                        help="Skip queries already in output file")
    args = parser.parse_args()

    # Determine query limit
    limit = args.max_queries or PHASE_LIMITS[args.phase]

    # Load queries
    if not os.path.exists(args.input):
        print(f"ERROR: Input file not found: {args.input}")
        print("Run bootstrap_datasets.py first: python scripts/bootstrap_datasets.py")
        sys.exit(1)

    with open(args.input, "r", encoding="utf-8") as f:
        queries = [json.loads(line) for line in f if line.strip()]

    if not queries:
        print("ERROR: No queries in input file")
        sys.exit(1)

    queries = queries[:limit]
    print(f"Loaded {len(queries)} queries (phase={args.phase}, limit={limit})")

    # Resume support: skip already-processed queries
    done_queries = set()
    if args.resume and os.path.exists(args.output):
        with open(args.output, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    row = json.loads(line)
                    done_queries.add(row.get("query", ""))
        print(f"Resuming: {len(done_queries)} queries already processed")
        queries = [q for q in queries if q["query"] not in done_queries]
        print(f"Remaining: {len(queries)} queries to send")

    # Check server
    print(f"\nChecking server at {args.url}...")
    if not check_server(args.url):
        print(f"ERROR: Server not reachable at {args.url}")
        print("Start the Flask app first (chat_rag mode)")
        sys.exit(1)
    print("Server is up.\n")

    # Rate limiting
    min_interval = 1.0 / args.rate if args.rate > 0 else 0

    # Stats
    stats = {
        "total": len(queries),
        "success": 0,
        "error": 0,
        "shadow_applied": 0,
        "rewrite_entered": 0,
        "suppressed": 0,
        "latencies_ms": [],
    }

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    mode = "a" if args.resume else "w"

    with open(args.output, mode, encoding="utf-8") as out_f:
        for i, q in enumerate(queries):
            query_text = q["query"]
            t0 = time.perf_counter()

            try:
                resp = send_query(args.url, query_text, timeout=args.timeout)
                t1 = time.perf_counter()
                latency_ms = round((t1 - t0) * 1000, 1)

                trace_summary = extract_trace_summary(resp)
                result = {
                    **q,
                    "response_length": len(resp.get("reply") or resp.get("response") or ""),
                    "latency_ms": latency_ms,
                    **trace_summary,
                }
                out_f.write(json.dumps(result, ensure_ascii=False) + "\n")
                out_f.flush()

                stats["success"] += 1
                stats["latencies_ms"].append(latency_ms)
                if trace_summary.get("reranker_shadow_applied"):
                    stats["shadow_applied"] += 1
                if trace_summary.get("rewrite_gate_entered"):
                    stats["rewrite_entered"] += 1
                if trace_summary.get("retrieval_suppressed"):
                    stats["suppressed"] += 1

                # Progress
                shadow_score = trace_summary.get("reranker_best_score")
                shadow_str = f"shadow={shadow_score:.3f}" if shadow_score is not None else "shadow=N/A"
                print(f"  [{i+1}/{len(queries)}] {latency_ms:>7.0f}ms | {shadow_str} | {query_text[:60]}")

            except urllib.error.HTTPError as e:
                t1 = time.perf_counter()
                latency_ms = round((t1 - t0) * 1000, 1)
                error_body = ""
                try:
                    error_body = e.read().decode("utf-8", errors="replace")[:200]
                except Exception:
                    pass
                print(f"  [{i+1}/{len(queries)}] HTTP {e.code} ({latency_ms:.0f}ms): {error_body[:80]}")
                stats["error"] += 1
                result = {**q, "error": f"HTTP {e.code}", "error_body": error_body, "latency_ms": latency_ms}
                out_f.write(json.dumps(result, ensure_ascii=False) + "\n")
                out_f.flush()

            except Exception as e:
                t1 = time.perf_counter()
                latency_ms = round((t1 - t0) * 1000, 1)
                print(f"  [{i+1}/{len(queries)}] ERROR ({latency_ms:.0f}ms): {e}")
                stats["error"] += 1
                result = {**q, "error": str(e)[:200], "latency_ms": latency_ms}
                out_f.write(json.dumps(result, ensure_ascii=False) + "\n")
                out_f.flush()

            # Rate limit
            elapsed = time.perf_counter() - t0
            if elapsed < min_interval:
                time.sleep(min_interval - elapsed)

    # Final report
    print(f"\n{'='*60}")
    print(f"Synthetic traffic complete")
    print(f"  Total:     {stats['total']}")
    print(f"  Success:   {stats['success']}")
    print(f"  Errors:    {stats['error']}")
    print(f"  Shadow applied: {stats['shadow_applied']}")
    print(f"  Rewrite entered: {stats['rewrite_entered']}")
    print(f"  Suppressed: {stats['suppressed']}")

    if stats["latencies_ms"]:
        lats = sorted(stats["latencies_ms"])
        p50 = lats[len(lats) // 2]
        p95 = lats[int(len(lats) * 0.95)]
        print(f"  Latency p50: {p50:.0f}ms")
        print(f"  Latency p95: {p95:.0f}ms")

    print(f"\nResults written to: {args.output}")
    print(f"Telemetry events persisted to database (is_internal=true)")


if __name__ == "__main__":
    main()
